name: DevSecOps CI

on:
  push:
  pull_request:

jobs:
  run-log-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run log checker
        run: bash ./log_checker.sh example.log

  build-docker:
    runs-on: ubuntu-latest
    needs: run-log-checker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t env-info .

      - name: Run container
        run: docker run --rm -e APP_ENV=CI env-info
